/**
 * Created By Nguyen Cong Thanh on 03/04/2019 15:28.
 *
 * Copyright Intelin 2019.
 */

const ACTION_TYPE = {}

// message center
ACTION_TYPE['MESSAGE_CENTER_UPDATE'] = 'MESSAGE_CENTER_UPDATE'

// public otp
ACTION_TYPE['PUBLIC_OTP_UPDATE'] = 'PUBLIC_OTP_UPDATE_KEY'
ACTION_TYPE['PUBLIC_OTP_RESEND'] = 'PUBLIC_OTP_RESEND'
ACTION_TYPE['PUBLIC_OTP_SEND'] = 'PUBLIC_OTP_SEND'

// public login
ACTION_TYPE['LOGIN_CHECK_USERNAME'] = 'LOGIN_CHECK_USERNAME'
ACTION_TYPE['LOGIN_CHECK_PASSWORD'] = 'LOGIN_CHECK_PASSWORD'
ACTION_TYPE['LOGIN_TRUST_DEVICE'] = 'LOGIN_TRUST_DEVICE'

// public forgot
ACTION_TYPE['FORGOT_SEND_INFO'] = 'FORGOT_SEND_INFO'
ACTION_TYPE['FORGOT_SEND_PASSWORD'] = 'FORGOT_SEND_PASSWORD'
ACTION_TYPE['FORGOT_GET_USERNAME']='FORGOT_GET_USERNAME'

// public register
ACTION_TYPE['REGISTER_SEND_INFO'] = 'REGISTER_SEND_INFO'
ACTION_TYPE['REGISTER_SEND_PHONE'] = 'REGISTER_SEND_PHONE'
ACTION_TYPE['REGISTER_SEND_ACCOUNT'] = 'REGISTER_SEND_ACCOUNT'
ACTION_TYPE['REGISTER_SEND_SCHEDULE'] = 'REGISTER_SEND_SCHEDULE'

export default ACTION_TYPE
