/**
 * Created By Nguyen Cong Thanh on 22/04/2019 17:51.
 *
 * Copyright Intelin 2019.
 */

const HTTP_CODE = {}

// 1xx Information
HTTP_CODE[HTTP_CODE["CONTINUE"] = 100] = "CONTINUE"
HTTP_CODE[HTTP_CODE["SWITCHING_PROTOCOLS"] = 101] = "SWITCHING_PROTOCOLS"
HTTP_CODE[HTTP_CODE["PROCESSING"] = 102] = "PROCESSING"

// 2xx Success
HTTP_CODE[HTTP_CODE["OK"] = 200] = "OK"
HTTP_CODE[HTTP_CODE["CREATED"] = 201] = "CREATED"
HTTP_CODE[HTTP_CODE["ACCEPTED"] = 202] = "ACCEPTED"
HTTP_CODE[HTTP_CODE["NON_AUTHORITATIVE_INFORMATION"] = 203] = "NON_AUTHORITATIVE_INFORMATION"
HTTP_CODE[HTTP_CODE["NO_CONTENT"] = 204] = "NO_CONTENT"
HTTP_CODE[HTTP_CODE["RESET_CONTENT"] = 205] = "RESET_CONTENT"
HTTP_CODE[HTTP_CODE["PARTIAL_CONTENT"] = 206] = "PARTIAL_CONTENT"
HTTP_CODE[HTTP_CODE["MULTI_STATUS"] = 207] = "MULTI_STATUS"
HTTP_CODE[HTTP_CODE["ALREADY_REPORTED"] = 208] = "ALREADY_REPORTED"
HTTP_CODE[HTTP_CODE["IM_USED"] = 226] = "IM_USED"

// 3xx Redirection
HTTP_CODE[HTTP_CODE["MULTIPLE_CHOICES"] = 300] = "MULTIPLE_CHOICES"
HTTP_CODE[HTTP_CODE["MOVED_PERMANENTLY"] = 301] = "MOVED_PERMANENTLY"
HTTP_CODE[HTTP_CODE["FOUND"] = 302] = "FOUND"
HTTP_CODE[HTTP_CODE["SEE_OTHER"] = 303] = "SEE_OTHER"
HTTP_CODE[HTTP_CODE["NOT_MODIFIED"] = 304] = "NOT_MODIFIED"
HTTP_CODE[HTTP_CODE["USE_PROXY"] = 305] = "USE_PROXY"
HTTP_CODE[HTTP_CODE["UNUSED"] = 306] = "UNUSED"
HTTP_CODE[HTTP_CODE["TEMPORARY_REDIRECT"] = 307] = "TEMPORARY_REDIRECT"
HTTP_CODE[HTTP_CODE["PERMANENT_REDIRECT"] = 308] = "PERMANENT_REDIRECT"

// 4xx Client Error
HTTP_CODE[HTTP_CODE["BAD_REQUEST"] = 400] = "BAD_REQUEST"
HTTP_CODE[HTTP_CODE["UNAUTHORIZED"] = 401] = "UNAUTHORIZED"
HTTP_CODE[HTTP_CODE["PAYMENT_REQUIRED"] = 402] = "PAYMENT_REQUIRED"
HTTP_CODE[HTTP_CODE["FORBIDDEN"] = 403] = "FORBIDDEN"
HTTP_CODE[HTTP_CODE["NOT_FOUND"] = 404] = "NOT_FOUND"
HTTP_CODE[HTTP_CODE["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED"
HTTP_CODE[HTTP_CODE["NOT_ACCEPTABLE"] = 406] = "NOT_ACCEPTABLE"
HTTP_CODE[HTTP_CODE["PROXY_AUTHENTICATION_REQUIRED"] = 407] = "PROXY_AUTHENTICATION_REQUIRED"
HTTP_CODE[HTTP_CODE["REQUEST_TIMEOUT"] = 408] = "REQUEST_TIMEOUT"
HTTP_CODE[HTTP_CODE["CONFLICT"] = 409] = "CONFLICT"
HTTP_CODE[HTTP_CODE["GONE"] = 410] = "GONE"
HTTP_CODE[HTTP_CODE["LENGTH_REQUIRED"] = 411] = "LENGTH_REQUIRED"
HTTP_CODE[HTTP_CODE["PRECONDITION_FAILED"] = 412] = "PRECONDITION_FAILED"
HTTP_CODE[HTTP_CODE["REQUEST_ENTITY_TOO_LARGE"] = 413] = "REQUEST_ENTITY_TOO_LARGE"
HTTP_CODE[HTTP_CODE["REQUEST_URI_TOO_LONG"] = 414] = "REQUEST_URI_TOO_LONG"
HTTP_CODE[HTTP_CODE["UNSUPPORTED_MEDIA_TYPE"] = 415] = "UNSUPPORTED_MEDIA_TYPE"
HTTP_CODE[HTTP_CODE["REQUESTED_RANGE_NOT_SATISFIABLE"] = 416] = "REQUESTED_RANGE_NOT_SATISFIABLE"
HTTP_CODE[HTTP_CODE["EXPECTATION_FAILED"] = 417] = "EXPECTATION_FAILED"
HTTP_CODE[HTTP_CODE["IM_A_TEAPOT"] = 418] = "IM_A_TEAPOT" // RFC 2324
HTTP_CODE[HTTP_CODE["ENCHANCE_YOUR_CALM"] = 420] = "ENCHANCE_YOUR_CALM"
HTTP_CODE[HTTP_CODE["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY"
HTTP_CODE[HTTP_CODE["LOCKED"] = 423] = "LOCKED"
HTTP_CODE[HTTP_CODE["FAILED_DEPENDENCY"] = 424] = "FAILED_DEPENDENCY"
HTTP_CODE[HTTP_CODE["RESERVED_FOR_WEBDAV"] = 425] = "RESERVED_FOR_WEBDAV"
HTTP_CODE[HTTP_CODE["UPGRADE_REQUIRED"] = 426] = "UPGRADE_REQUIRED"
HTTP_CODE[HTTP_CODE["PRECONDITION_REQUIRED"] = 428] = "PRECONDITION_REQUIRED"
HTTP_CODE[HTTP_CODE["TOO_MANY_REQUESTS"] = 429] = "TOO_MANY_REQUESTS"
HTTP_CODE[HTTP_CODE["TOO_MANY_REQUESTS"] = 431] = "TOO_MANY_REQUESTS"
HTTP_CODE[HTTP_CODE["NO_RESPONSE"] = 444] = "NO_RESPONSE" // nginx
HTTP_CODE[HTTP_CODE["RETRY_WITH"] = 449] = "RETRY_WITH"
HTTP_CODE[HTTP_CODE["BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS"] = 450] = "BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS"
HTTP_CODE[HTTP_CODE["UNAVAILABLE_FOR_LEGAL_REASONS"] = 451] = "UNAVAILABLE_FOR_LEGAL_REASONS"
HTTP_CODE[HTTP_CODE["CLIENT_CLOSED_REQUEST"] = 499] = "UNAVAILABLE_FOR_LEGAL_REASONS" // nginx

// 5xx Server Error
HTTP_CODE[HTTP_CODE["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR"
HTTP_CODE[HTTP_CODE["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED"
HTTP_CODE[HTTP_CODE["BAD_GATEWAY"] = 502] = "BAD_GATEWAY"
HTTP_CODE[HTTP_CODE["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE"
HTTP_CODE[HTTP_CODE["GATEWAY_TIMEOUT"] = 504] = "GATEWAY_TIMEOUT"
HTTP_CODE[HTTP_CODE["HTTP_VERSION_NOT_SUPPORTED"] = 505] = "HTTP_VERSION_NOT_SUPPORTED"
HTTP_CODE[HTTP_CODE["INSUFFICIENT_STORAGE"] = 507] = "INSUFFICIENT_STORAGE"
HTTP_CODE[HTTP_CODE["LOOP_DETECTED"] = 508] = "LOOP_DETECTED"
HTTP_CODE[HTTP_CODE["BANDWIDTH_LIMIT_EXCEEDED"] = 509] = "BANDWIDTH_LIMIT_EXCEEDED"
HTTP_CODE[HTTP_CODE["NOT_EXTENDED"] = 510] = "NOT_EXTENDED"
HTTP_CODE[HTTP_CODE["NETWORK_AUTHENTICATION_REQUIRE"] = 511] = "NETWORK_AUTHENTICATION_REQUIRE"
HTTP_CODE[HTTP_CODE["NETWORK_READ_TIMEOUT_ERROR"] = 598] = "NETWORK_READ_TIMEOUT_ERROR"
HTTP_CODE[HTTP_CODE["NETWORK_CONNECT_TIMEOUT_ERROR"] = 599] = "NETWORK_CONNECT_TIMEOUT_ERROR"

export default HTTP_CODE
