/**
 * Created By Nguyen Cong Thanh on 14/09/2019 20:53.
 *
 * Copyright Intelin 2019.
 */

import LocalizeKey from '../../constants/localize'

const CODE_ERROR = {}

// Login
CODE_ERROR[CODE_ERROR["LOGIN_USER_BLOCKED_BY_ADMIN"] = 'LOGIN_4002'] = 'Login user blocked by admin'
CODE_ERROR[CODE_ERROR["LOGIN_USER_BANNED"] = 'LOGIN_4003'] = "Login user banned"
CODE_ERROR[CODE_ERROR["LOGIN_NOT_FOUND_USERNAME"] = 'LOGIN_4004'] = LocalizeKey.LOGIN_VALIDATION_USERNAME_NOT_EXIST
CODE_ERROR[CODE_ERROR["LOGIN_PASSWORD_NOT_MATCH"] = 'LOGIN_4005'] = LocalizeKey.LOGIN_VALIDATION_PASSWORD_INCORRECT

// Register
CODE_ERROR[CODE_ERROR["REGISTER_NOT_FOUND_USER"] = '4041'] = 'Not Found User'
CODE_ERROR[CODE_ERROR["REGISTER_CREATE_MEETING_SCHEDULE_FAILED"] = 'REGISTER_4002'] = 'Create meeting schedule for register failed'
CODE_ERROR[CODE_ERROR["REGISTER_ADMIN_UPDATE_TEMP_USER_FAILED"] = 'REGISTER_4003'] = 'Admin update info temp user failed'
CODE_ERROR[CODE_ERROR["REGISTER_ADMIN_APPROVE_USER_FAILED"] = 'REGISTER_4004'] = 'Admin approve user failed'
CODE_ERROR[CODE_ERROR["REGISTER_DUPLICATE_LICENSE"] = 'CONFLICT_4000'] = 'Duplicate license'
CODE_ERROR[CODE_ERROR["REGISTER_DUPLICATE_USERNAME"] = 'CONFLICT_4001'] = 'Duplicate username'

// Forgot
CODE_ERROR[CODE_ERROR["FORGOT_USER_NOT_FOUND"] = 'USER_4000'] = LocalizeKey.FORGOT_VALIDATION_WRONG_ENTER_INFO
CODE_ERROR[CODE_ERROR["FORGOT_UPDATE_PASSWORD_FAILED"] = 'PASSWORD_4000'] = 'Update password failed'

// Public otp
CODE_ERROR[CODE_ERROR["OTP_NOT_MATCH"] = 'OTP_4000'] = 'Otp not match'
CODE_ERROR[CODE_ERROR["OTP_CODE_EXPIRED"] = 'OTP_4001'] = 'Otp was expired'
CODE_ERROR[CODE_ERROR["OTP_TRANSACTION_FAILED"] = 'OTP_4002'] = 'Otp transaction was failed'



export default CODE_ERROR
